name: Scan with OWASP Dependency Check

# Define when the workflow should be triggered
on:
    push:
      branches:
        - development # Trigger when code is pushed to the 'development' branch
        - main # Trigger when code is pushed to the 'main' branch

jobs:
  depchecktest:
    name: Scan with OWASP Dependency Check
    
    runs-on: [ 'ubuntu-latest' ] # Use the latest version of Ubuntu
    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Action to check out the code from the repository
        # This step fetches the codebase from the GitHub repository

      - name: Build project with Maven
        run: mvn clean install

      - name: Scan with OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Mutillidae'
          path: '.'
          format: 'SARIF'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired

      - name: Upload results from Snyk to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif
          # Action to upload the results of the Snyk scan in SARIF format