on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push results
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history to avoid pull issues

      - name: Check Semgrep Token
        run: |
          echo "Checking Semgrep token..."
          [[ -n "$SEMGREP_APP_TOKEN" ]] && echo "Token exists" || echo "Token is missing!"

      - name: Run Semgrep Scan
        run: semgrep ci --json > semgrep-sast-results.json

      - name: Convert JSON to CSV
        run: |
          jq -r '.results | map([.path, .start.line, .check_id, .extra.message] | @csv) | join("\n")' semgrep-sast-results.json > semgrep-sast-results.csv
          echo "timestamp,$(date)" >> semgrep-sast-results.csv  # Ensure changes for git commit

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add semgrep-sast-results.csv
          git diff --cached --quiet || git commit -m "Add Semgrep SAST scan results"
          git push origin main
