on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml

name: Semgrep

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Changed to write to allow pushing results
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci --json > semgrep-sast-results.json
    - run: jq -r '.results | map([.path, .start.line, .check_id, .extra.message] | @csv) | join("\n")' semgrep-sast-results.json > semgrep-sast-results.csv
    - name: Commit and Push Results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add semgrep-sast-results.csv
        git commit -m "Add Semgrep SAST scan results"
        git push origin main
